export const HOME_PAGE_BLOCKS = [
  {
    styles:
      "#styles:,min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-100 text-foreground antialiased relative overflow-hidden",
    backgroundImage: "",
    tag: "div",
    _type: "Box",
    _id: "AepDbh",
    _name: "Box",
  },
  {
    styles: "#styles:,absolute inset-0 opacity-20",
    backgroundImage: "",
    tag: "div",
    _type: "Box",
    _id: "BzidDl",
    _name: "Background Pattern",
    _parent: "AepDbh",
  },
  {
    styles: "#styles:, w-16px h-16px absolute inset-0 h-full w-full",
    icon: "<svg xmlns='http://www.w3.org/2000/svg'><defs><pattern id='hexagons' width='80' height='69.28' patternUnits='userSpaceOnUse'><path d='M40 0L60 20L60 40L40 60L20 40L20 20Z' fill='none' stroke='rgb(99 102 241)' stroke-width='1' opacity='0.15'></path></pattern><pattern id='waves' width='100' height='20' patternUnits='userSpaceOnUse'><path d='M0 10 Q25 0 50 10 T100 10' fill='none' stroke='rgb(79 70 229)' stroke-width='1' opacity='0.1'></path></pattern><pattern id='triangles' width='40' height='40' patternUnits='userSpaceOnUse'><polygon points='20,5 35,30 5,30' fill='none' stroke='rgb(129 140 248)' stroke-width='1' opacity='0.08'></polygon></pattern></defs><rect width='100%' height='100%' fill='url(#hexagons)'></rect><rect width='100%' height='100%' fill='url(#waves)'></rect><rect width='100%' height='100%' fill='url(#triangles)'></rect></svg>",
    width: "16",
    height: "16",
    _type: "Icon",
    _id: "otypid",
    _parent: "BzidDl",
  },
  {
    styles: "#styles:,min-h-screen flex flex-col",
    backgroundImage: "",
    tag: "main",
    _type: "Box",
    _id: "tcvjzk",
    _name: "Main Content",
    _parent: "AepDbh",
  },
  {
    styles: "#styles:,flex-1 flex items-center justify-center px-4 sm:px-6 lg:px-8",
    backgroundImage: "",
    tag: "section",
    _type: "Box",
    _id: "dijaom",
    _name: "Hero Section",
    _parent: "tcvjzk",
  },
  {
    styles: "#styles:,max-w-3xl mx-auto text-center space-y-8 relative z-10",
    backgroundImage: "",
    tag: "div",
    _type: "Box",
    _id: "jicCuz",
    _name: "Hero Content",
    _parent: "dijaom",
  },
  {
    styles: "#styles:,flex items-center justify-center space-x-3 mb-6",
    backgroundImage: "",
    tag: "div",
    _type: "Box",
    _id: "lswoxD",
    _name: "Logo Section",
    _parent: "jicCuz",
  },
  {
    styles: "#styles:,w-12 h-12 bg-primary rounded-xl flex items-center justify-center shadow-lg",
    backgroundImage: "",
    tag: "div",
    _type: "Box",
    _id: "jqAmjw",
    _name: "Box",
    _parent: "lswoxD",
  },
  {
    styles: "#styles:, w-28px h-28px w-7 h-7 text-primary-foreground",
    icon: "<svg fill='currentColor' viewBox='0 0 20 20'><path d='M3 4a1 1 0 011-1h12a1 1 0 011 1v2a1 1 0 01-1 1H4a1 1 0 01-1-1V4zM3 10a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H4a1 1 0 01-1-1v-6zM14 9a1 1 0 00-1 1v6a1 1 0 001 1h2a1 1 0 001-1v-6a1 1 0 00-1-1h-2z'></path></svg>",
    width: "28",
    height: "28",
    _type: "Icon",
    _id: "dBryxn",
    _parent: "jqAmjw",
  },
  {
    styles: "#styles:,text-2xl font-bold",
    content: "Builder",
    _type: "Span",
    _id: "tAjdia",
    _parent: "lswoxD",
    tag: "span",
  },
  {
    styles:
      "#styles:,inline-flex items-center rounded-full border border-border bg-secondary px-3 py-1 text-sm font-medium text-secondary-foreground",
    backgroundImage: "",
    tag: "div",
    _type: "Box",
    _id: "cwCvha",
    _name: "Welcome Badge",
    _parent: "jicCuz",
  },
  {
    styles: "#styles:, w-16px h-16px mr-2 h-4 w-4",
    icon: "<svg fill='currentColor' viewBox='0 0 20 20'><path fill-rule='evenodd' d='M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z' clip-rule='evenodd'></path></svg>",
    width: "16",
    height: "16",
    _type: "Icon",
    _id: "knyxmC",
    _parent: "cwCvha",
  },
  {
    styles: "#styles:,text-black",
    content: " Welcome to Builder ",
    _type: "Text",
    _id: "miDjCw",
    _parent: "cwCvha",
  },
  {
    styles: "#styles:,space-y-4",
    backgroundImage: "",
    tag: "div",
    _type: "Box",
    _id: "Bcqlkg",
    _name: "Main Heading",
    _parent: "jicCuz",
  },
  {
    tag: "h1",
    styles: "#styles:,text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight",
    content: "Heading goes here",
    _type: "Heading",
    _id: "xxxzCj",
    _parent: "Bcqlkg",
  },
  {
    styles: "#styles:,text-black",
    content: " Build amazing experiences ",
    _type: "Text",
    _id: "vaBvBr",
    _parent: "xxxzCj",
  },
  {
    styles: "#styles:,text-muted-foreground",
    content: "with ease",
    _type: "Span",
    _id: "xqerbo",
    _parent: "xxxzCj",
    tag: "span",
  },
  {
    styles: "#styles:,text-lg sm:text-xl text-muted-foreground max-w-2xl mx-auto leading-relaxed",
    content:
      " Get started with our powerful builder platform. Create, customize, and deploy your projects in minutes, not hours. ",
    _type: "Paragraph",
    _id: "vicqyb",
    _parent: "Bcqlkg",
  },
  {
    styles: "#styles:,flex flex-wrap items-center justify-center gap-2 pt-8",
    backgroundImage: "",
    tag: "div",
    _type: "Box",
    _id: "etinst",
    _name: "Feature Pills",
    _parent: "jicCuz",
  },
  {
    styles:
      "#styles:,inline-flex items-center rounded-full bg-muted px-3 py-1 text-xs font-medium text-muted-foreground",
    content: " ⚡ Fast Setup ",
    _type: "Span",
    _id: "yprAAb",
    _parent: "etinst",
    tag: "span",
  },
  {
    styles:
      "#styles:,inline-flex items-center rounded-full bg-muted px-3 py-1 text-xs font-medium text-muted-foreground",
    content: " 🎨 Customizable ",
    _type: "Span",
    _id: "eDDyka",
    _parent: "etinst",
    tag: "span",
  },
  {
    styles:
      "#styles:,inline-flex items-center rounded-full bg-muted px-3 py-1 text-xs font-medium text-muted-foreground",
    content: " 📱 Responsive ",
    _type: "Span",
    _id: "csAjyt",
    _parent: "etinst",
    tag: "span",
  },
  {
    styles:
      "#styles:,inline-flex items-center rounded-full bg-muted px-3 py-1 text-xs font-medium text-muted-foreground",
    content: " 🚀 Deploy Ready ",
    _type: "Span",
    _id: "wmhfxq",
    _parent: "etinst",
    tag: "span",
  },
  {
    styles: "#styles:,border-t border-border/20 bg-white/10 backdrop-blur-sm mt-auto relative z-10",
    backgroundImage: "",
    tag: "footer",
    _type: "Box",
    _id: "gdbitf",
    _name: "Site Footer",
    _parent: "tcvjzk",
  },
  {
    styles: "#styles:,container mx-auto px-4 sm:px-6 lg:px-8 py-6",
    backgroundImage: "",
    tag: "div",
    _type: "Box",
    _id: "Bgzhaz",
    _name: "Box",
    _parent: "gdbitf",
  },
  {
    styles: "#styles:,flex flex-col sm:flex-row items-center justify-between gap-4",
    backgroundImage: "",
    tag: "div",
    _type: "Box",
    _id: "cecuDt",
    _name: "Footer Content",
    _parent: "Bgzhaz",
  },
  {
    styles: "#styles:,flex items-center space-x-4 text-sm text-muted-foreground",
    backgroundImage: "",
    tag: "div",
    _type: "Box",
    _id: "kDrinz",
    _name: "Footer Links",
    _parent: "cecuDt",
  },
  {
    styles: "#styles:,hover:text-foreground transition-colors",
    content: "Privacy",
    link: {
      href: "#",
    },
    prefetchLink: false,
    _type: "Link",
    _id: "DgCjkf",
    _parent: "kDrinz",
  },
  {
    styles: "#styles:,hover:text-foreground transition-colors",
    content: "Terms",
    link: {
      href: "#",
    },
    prefetchLink: false,
    _type: "Link",
    _id: "jhzixr",
    _parent: "kDrinz",
  },
  {
    styles: "#styles:,hover:text-foreground transition-colors",
    content: "Contact",
    link: {
      href: "#",
    },
    prefetchLink: false,
    _type: "Link",
    _id: "hqtamg",
    _parent: "kDrinz",
  },
  {
    styles: "#styles:,text-sm text-muted-foreground",
    content: " © 2024 Builder. All rights reserved. ",
    _type: "Paragraph",
    _id: "zyofbC",
    _parent: "cecuDt",
  },
  {
    _type: "@chai/ai-context",
    _value: "",
  },
];
