export const HOME_PAGE_BLOCKS = [
  {
    styles:
      "#styles:,flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-background to-muted px-4 py-12 text-center",
    backgroundImage: "",
    tag: "div",
    _id: "htokkt",
    _type: "Box",
    _name: "Box",
  },
  {
    styles: "#styles:,mx-auto max-w-3xl",
    backgroundImage: "",
    tag: "div",
    _id: "hDDCgq",
    _parent: "htokkt",
    _type: "Box",
    _name: "Box",
  },
  {
    styles: "#styles:,mb-8 flex justify-center",
    backgroundImage: "",
    tag: "div",
    _id: "rygmAv",
    _parent: "hDDCgq",
    _type: "Box",
    _name: "Box",
  },
  {
    styles:
      "#styles:,relative h-16 w-16 overflow-hidden rounded-full bg-card p-2 shadow-lg ring-1 ring-border",
    backgroundImage: "",
    tag: "div",
    _id: "Axvdgo",
    _parent: "rygmAv",
    _type: "Box",
    _name: "Box",
  },
  {
    styles: "#styles:,absolute inset-0 flex items-center justify-center",
    backgroundImage: "",
    tag: "div",
    _id: "oCgzhC",
    _parent: "Axvdgo",
    _type: "Box",
    _name: "Box",
  },
  {
    tag: "h1",
    styles:
      "#styles:,mb-4 bg-gradient-to-r from-primary to-primary/60 bg-clip-text text-4xl font-extrabold tracking-tight text-transparent sm:text-5xl md:text-6xl",
    content: "Welcome to Chai Builder",
    _id: "CdthDe",
    _parent: "hDDCgq",
    _type: "Heading",
  },
  {
    styles: "#styles:,mb-8 text-lg text-foreground/80",
    content: "",
    _id: "beojiy",
    _parent: "hDDCgq",
    _type: "Paragraph",
  },
  {
    styles: "#styles:,text-black",
    content: "Start editing this page. Login to builder at ",
    _id: "iajsrw",
    _parent: "beojiy",
    _type: "Text",
  },
  {
    styles:
      "#styles:,relative rounded bg-muted px-[0.3rem] py-[0.2rem] font-mono text-sm font-semibold text-foreground inline",
    backgroundImage: "",
    tag: "div",
    _id: "jvlaku",
    _parent: "beojiy",
    _type: "Box",
    _name: "Code",
  },
  {
    styles: "#styles:,text-black",
    content: "/chai",
    _id: "pBkiab",
    _parent: "jvlaku",
    _type: "Text",
  },
  {
    styles: "#styles:,text-black",
    content: ".",
    _id: "AyfCqB",
    _parent: "beojiy",
    _type: "Text",
  },
  {
    styles: "#styles:,mb-12",
    backgroundImage: "",
    tag: "div",
    _id: "ozAlxu",
    _parent: "hDDCgq",
    _type: "Box",
    _name: "Box",
  },
  {
    styles:
      "#styles:,group inline-flex items-center justify-center gap-2 rounded-full bg-primary px-6 py-3 text-sm font-medium text-primary-foreground transition-all hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2",
    content: "Link goes here",
    link: { href: "/chai" },
    _id: "DrCjab",
    _parent: "ozAlxu",
    _type: "Link",
  },
  {
    styles: "#styles:,text-black",
    content: "Get Started",
    _id: "Cnyynx",
    _parent: "DrCjab",
    _type: "Text",
  },
  {
    styles:
      "#styles:, lucide lucide-arrow-right h-4 w-4 transition-transform group-hover:translate-x-1",
    icon: "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M5 12h14'></path><path d='m12 5 7 7-7 7'></path></svg>",
    width: 16,
    height: 16,
    _id: "hjyklc",
    _parent: "DrCjab",
    _type: "Icon",
  },
  {
    styles: "#styles:,text-sm text-muted-foreground",
    content: "Happy Building. Best of luck!",
    _id: "qnkbdy",
    _parent: "hDDCgq",
    _type: "Paragraph",
  },
  {
    styles:
      "#styles:,absolute inset-0 -z-10 h-full w-full bg-background bg-[linear-gradient(to_right,hsl(var(--border))_1px,transparent_1px),linear-gradient(to_bottom,hsl(var(--border))_1px,transparent_1px)] bg-[size:4rem_4rem] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_0%,#000_70%,transparent_110%)]",
    backgroundImage: "",
    _id: "vgBeam",
    _parent: "hDDCgq",
    _type: "EmptyBox",
    tag: "div",
    _name: "EmptyBox",
  },
  {
    _type: "Image",
    _id: "qoucAg",
    styles: "#styles:,",
    image:
      "https://fldwljgzcktqnysdkxnn.supabase.co/storage/v1/object/public/dam-assets/07f9192d-3b5d-4187-b13a-f05caee11176/gVH7O-Ir_400x400.png",
    alt: "",
    lazyLoading: true,
    width: "50",
    height: "50",
    mobileImage: "",
    assetId: "",
    _parent: "oCgzhC",
  },
];
