export const HOME_PAGE_BLOCKS = [
  {
    _id: "AepDbh",
    _type: "Box",
    tag: "div",
    _name: "Box",
    styles:
      "#styles:,min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-100 text-foreground antialiased relative overflow-hidden",
  },
  {
    _id: "BzidDl",
    _parent: "AepDbh",
    _type: "Box",
    tag: "div",
    _name: "Background Pattern",
    styles: "#styles:,absolute inset-0 opacity-20",
  },
  {
    _id: "otypid",
    _parent: "BzidDl",
    _type: "Icon",
    styles: "#styles:, w-16px h-16px absolute inset-0 h-full w-full",
    height: "16",
    width: "16",
    icon: "<svg xmlns='http://www.w3.org/2000/svg'><defs><pattern id='hexagons' width='80' height='69.28' patternUnits='userSpaceOnUse'><path d='M40 0L60 20L60 40L40 60L20 40L20 20Z' fill='none' stroke='rgb(99 102 241)' stroke-width='1' opacity='0.15'></path></pattern><pattern id='waves' width='100' height='20' patternUnits='userSpaceOnUse'><path d='M0 10 Q25 0 50 10 T100 10' fill='none' stroke='rgb(79 70 229)' stroke-width='1' opacity='0.1'></path></pattern><pattern id='triangles' width='40' height='40' patternUnits='userSpaceOnUse'><polygon points='20,5 35,30 5,30' fill='none' stroke='rgb(129 140 248)' stroke-width='1' opacity='0.08'></polygon></pattern></defs><rect width='100%' height='100%' fill='url(#hexagons)'></rect><rect width='100%' height='100%' fill='url(#waves)'></rect><rect width='100%' height='100%' fill='url(#triangles)'></rect></svg>",
  },
  {
    _id: "tcvjzk",
    _parent: "AepDbh",
    _type: "Box",
    tag: "main",
    _name: "Main Content",
    styles: "#styles:,min-h-screen flex flex-col",
  },
  {
    _id: "dijaom",
    _parent: "tcvjzk",
    _type: "Box",
    tag: "section",
    _name: "Hero Section",
    styles: "#styles:,flex-1 flex items-center justify-center px-4 sm:px-6 lg:px-8",
  },
  {
    _id: "jicCuz",
    _parent: "dijaom",
    _type: "Box",
    tag: "div",
    _name: "Hero Content",
    styles: "#styles:,max-w-3xl mx-auto text-center space-y-8 relative z-10",
  },
  {
    _id: "lswoxD",
    _parent: "jicCuz",
    _type: "Box",
    tag: "div",
    _name: "Logo Section",
    styles: "#styles:,flex items-center justify-center space-x-3 mb-6",
  },
  {
    _id: "jqAmjw",
    _parent: "lswoxD",
    _type: "Box",
    tag: "div",
    _name: "Box",
    styles: "#styles:,w-12 h-12 bg-primary rounded-xl flex items-center justify-center shadow-lg",
  },
  {
    _id: "dBryxn",
    _parent: "jqAmjw",
    _type: "Icon",
    styles: "#styles:, w-28px h-28px w-7 h-7 text-primary-foreground",
    height: "28",
    width: "28",
    icon: "<svg fill='currentColor' viewBox='0 0 20 20'><path d='M3 4a1 1 0 011-1h12a1 1 0 011 1v2a1 1 0 01-1 1H4a1 1 0 01-1-1V4zM3 10a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H4a1 1 0 01-1-1v-6zM14 9a1 1 0 00-1 1v6a1 1 0 001 1h2a1 1 0 001-1v-6a1 1 0 00-1-1h-2z'></path></svg>",
  },
  {
    _id: "tAjdia",
    _parent: "lswoxD",
    _type: "Span",
    tag: "span",
    styles: "#styles:,text-2xl font-bold",
    content: "Builder",
  },
  {
    _id: "cwCvha",
    _parent: "jicCuz",
    _type: "Box",
    tag: "div",
    _name: "Welcome Badge",
    styles:
      "#styles:,inline-flex items-center rounded-full border border-border bg-secondary px-3 py-1 text-sm font-medium text-secondary-foreground",
  },
  {
    _id: "knyxmC",
    _parent: "cwCvha",
    _type: "Icon",
    styles: "#styles:, w-16px h-16px mr-2 h-4 w-4",
    height: "16",
    width: "16",
    icon: "<svg fill='currentColor' viewBox='0 0 20 20'><path fill-rule='evenodd' d='M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z' clip-rule='evenodd'></path></svg>",
  },
  {
    _id: "miDjCw",
    _parent: "cwCvha",
    _type: "Text",
    content: " Welcome to Builder ",
  },
  {
    _id: "Bcqlkg",
    _parent: "jicCuz",
    _type: "Box",
    tag: "div",
    _name: "Main Heading",
    styles: "#styles:,space-y-4",
  },
  {
    _id: "xxxzCj",
    _parent: "Bcqlkg",
    _type: "Heading",
    tag: "h1",
    styles: "#styles:,text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight",
  },
  {
    _id: "vaBvBr",
    _parent: "xxxzCj",
    _type: "Text",
    content: " Build amazing experiences ",
  },
  {
    _id: "xqerbo",
    _parent: "xxxzCj",
    _type: "Span",
    tag: "span",
    styles: "#styles:,text-muted-foreground",
    content: "with ease",
  },
  {
    _id: "vicqyb",
    _parent: "Bcqlkg",
    _type: "Paragraph",
    content:
      " Get started with our powerful builder platform. Create, customize, and deploy your projects in minutes, not hours. ",
    styles: "#styles:,text-lg sm:text-xl text-muted-foreground max-w-2xl mx-auto leading-relaxed",
  },
  {
    _id: "yrvDrq",
    _parent: "jicCuz",
    _type: "Box",
    tag: "div",
    _name: "Action Buttons",
    styles: "#styles:,flex flex-col sm:flex-row items-center justify-center gap-4 pt-4",
  },
  {
    _id: "hudBiz",
    _parent: "yrvDrq",
    _type: "Button",
    styles_attrs: {
      onclick: "window.open('#', '_blank')",
      "aria-label": "Go to builder interface",
    },
    styles:
      "#styles:,inline-flex items-center justify-center rounded-md bg-primary px-8 py-3 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 w-full sm:w-auto",
  },
  {
    _id: "czDwih",
    _parent: "hudBiz",
    _type: "Icon",
    styles: "#styles:, w-16px h-16px mr-2 h-4 w-4",
    height: "16",
    width: "16",
    icon: "<svg fill='none' stroke='currentColor' viewBox='0 0 24 24'><path stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M13 10V3L4 14h7v7l9-11h-7z'></path></svg>",
  },
  {
    _id: "bmhcrd",
    _parent: "hudBiz",
    _type: "Text",
    content: " Go to Builder ",
  },
  {
    _id: "iCndiC",
    _parent: "yrvDrq",
    _type: "Button",
    styles_attrs: {
      onclick: "window.open('#', '_blank')",
      "aria-label": "Read documentation",
    },
    styles:
      "#styles:,inline-flex items-center justify-center rounded-md border border-border bg-background px-8 py-3 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 w-full sm:w-auto",
  },
  {
    _id: "jpefzp",
    _parent: "iCndiC",
    _type: "Icon",
    styles: "#styles:, w-16px h-16px mr-2 h-4 w-4",
    height: "16",
    width: "16",
    icon: "<svg fill='none' stroke='currentColor' viewBox='0 0 24 24'><path stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.746 0 3.332.477 4.5 1.253v13C19.832 18.477 18.246 18 16.5 18c-1.746 0-3.332.477-4.5 1.253'></path></svg>",
  },
  {
    _id: "tuukid",
    _parent: "iCndiC",
    _type: "Text",
    content: " Read Docs ",
  },
  {
    _id: "etinst",
    _parent: "jicCuz",
    _type: "Box",
    tag: "div",
    _name: "Feature Pills",
    styles: "#styles:,flex flex-wrap items-center justify-center gap-2 pt-8",
  },
  {
    _id: "yprAAb",
    _parent: "etinst",
    _type: "Span",
    tag: "span",
    styles:
      "#styles:,inline-flex items-center rounded-full bg-muted px-3 py-1 text-xs font-medium text-muted-foreground",
    content: " ⚡ Fast Setup ",
  },
  {
    _id: "eDDyka",
    _parent: "etinst",
    _type: "Span",
    tag: "span",
    styles:
      "#styles:,inline-flex items-center rounded-full bg-muted px-3 py-1 text-xs font-medium text-muted-foreground",
    content: " 🎨 Customizable ",
  },
  {
    _id: "csAjyt",
    _parent: "etinst",
    _type: "Span",
    tag: "span",
    styles:
      "#styles:,inline-flex items-center rounded-full bg-muted px-3 py-1 text-xs font-medium text-muted-foreground",
    content: " 📱 Responsive ",
  },
  {
    _id: "wmhfxq",
    _parent: "etinst",
    _type: "Span",
    tag: "span",
    styles:
      "#styles:,inline-flex items-center rounded-full bg-muted px-3 py-1 text-xs font-medium text-muted-foreground",
    content: " 🚀 Deploy Ready ",
  },
  {
    _id: "gdbitf",
    _parent: "tcvjzk",
    _type: "Box",
    tag: "footer",
    _name: "Site Footer",
    styles: "#styles:,border-t border-border/20 bg-white/10 backdrop-blur-sm mt-auto relative z-10",
  },
  {
    _id: "Bgzhaz",
    _parent: "gdbitf",
    _type: "Box",
    tag: "div",
    _name: "Box",
    styles: "#styles:,container mx-auto px-4 sm:px-6 lg:px-8 py-6",
  },
  {
    _id: "cecuDt",
    _parent: "Bgzhaz",
    _type: "Box",
    tag: "div",
    _name: "Footer Content",
    styles: "#styles:,flex flex-col sm:flex-row items-center justify-between gap-4",
  },
  {
    _id: "kDrinz",
    _parent: "cecuDt",
    _type: "Box",
    tag: "div",
    _name: "Footer Links",
    styles: "#styles:,flex items-center space-x-4 text-sm text-muted-foreground",
  },
  {
    _id: "DgCjkf",
    _parent: "kDrinz",
    _type: "Link",
    link: {
      href: "#",
    },
    styles: "#styles:,hover:text-foreground transition-colors",
    content: "Privacy",
  },
  {
    _id: "jhzixr",
    _parent: "kDrinz",
    _type: "Link",
    link: {
      href: "#",
    },
    styles: "#styles:,hover:text-foreground transition-colors",
    content: "Terms",
  },
  {
    _id: "hqtamg",
    _parent: "kDrinz",
    _type: "Link",
    link: {
      href: "#",
    },
    styles: "#styles:,hover:text-foreground transition-colors",
    content: "Contact",
  },
  {
    _id: "zyofbC",
    _parent: "cecuDt",
    _type: "Paragraph",
    content: " © 2024 Builder. All rights reserved. ",
    styles: "#styles:,text-sm text-muted-foreground",
  },
];
