import { getBrandConfig } from "@/lib/utils";
import type { Metadata } from "next";
import { Geist } from "next/font/google";

import "./builder.css";

const geist = Geist({ subsets: ["latin"] });

const brandConfig = getBrandConfig();

export const metadata: Metadata = {
  title: `${brandConfig.name || "Your Brand"} - Editor`,
  description: "Generated by create turbo",
  icons: {
    icon: brandConfig.favicon || "/favicon.ico",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={geist.className}>{children}</body>
    </html>
  );
}
