import type { Metadata } from "next";
import { Geist } from "next/font/google";

import "./builder.css";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Your Brand - Editor",
  description: "Generated by create turbo",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={geist.className}>{children}</body>
    </html>
  );
}
