import { getBrandConfig } from "@/lib/utils";
import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { CrispChatWidget } from "@/components/crisp-chat-widget";
import { isEmpty } from "lodash";
import Script from "next/script";
import "./builder.css";

const geist = Geist({ subsets: ["latin"], preload: true });

const brandConfig = getBrandConfig();

export const metadata: Metadata = {
  title: `${brandConfig.name || "Your Brand"} - Editor`,
  description: "Generated by create turbo",
  icons: {
    icon: brandConfig.favicon || "/favicon.ico",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={geist.className}>
        {children}
        {!isEmpty(process.env.NEXT_PUBLIC_CLARITY_ID) ? (
          <Script
            id="chaibuilder-app-clarity"
            strategy="afterInteractive"
            dangerouslySetInnerHTML={{
              __html: `
          (function(c,l,a,r,i,t,y){
            c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
            t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
            y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
          })(window, document, "clarity", "script", "${process.env.NEXT_PUBLIC_CLARITY_ID}");
        `,
            }}
          />
        ) : null}
        <CrispChatWidget />
      </body>
    </html>
  );
}
